"""update relationships in Payment and Booking

Revision ID: 2003c0007398
Revises: d3c224a65132
Create Date: 2024-01-02 23:30:48.507252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2003c0007398'
down_revision: Union[str, None] = 'd3c224a65132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookings_payment_id_fkey', 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('bookings_payment_id_fkey', 'bookings', 'payments', ['payment_id'], ['id'])
    # ### end Alembic commands ###
