"""Add booking_date column to bookings table

Revision ID: 3810a69348c7
Revises: ae2c29906ced
Create Date: 2024-01-25 20:48:42.128776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3810a69348c7'
down_revision: Union[str, None] = 'ae2c29906ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'booking_date')
    # ### end Alembic commands ###
