"""Add payment_id column to bookings table

Revision ID: c1c2d96b694c
Revises: 3810a69348c7
Create Date: 2024-01-25 23:48:11.198695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c2d96b694c'
down_revision: Union[str, None] = '3810a69348c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('payment_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'payment_id')
    # ### end Alembic commands ###
