"""Add order_id and created_at to payments table

Revision ID: c67076905969
Revises: c1c2d96b694c
Create Date: 2024-01-26 01:19:04.863429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c67076905969'
down_revision: Union[str, None] = 'c1c2d96b694c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('order_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text('now()')))


def downgrade() -> None:
    pass